DROP TABLE IF EXISTS "Telefone" CASCADE;
DROP TABLE IF EXISTS "Contato" CASCADE;

CREATE TABLE "Contato" (
    "ID" NUMERIC(14) PRIMARY KEY,
    "NOME" VARCHAR(100),
    "IDADE" NUMERIC(3)
);

CREATE TABLE "Telefone" (
    "IDCONTATO" NUMERIC(14),
    "ID" NUMERIC(14),
    "NUMERO" VARCHAR(16),
    CONSTRAINT "pk_phones" PRIMARY KEY ("IDCONTATO", "ID"),
    CONSTRAINT "fk_phones_contact" FOREIGN KEY ("IDCONTATO") REFERENCES "Contato"("ID")
);